### ISSUE TITLE
Not able to remove word that ends with spaces

### ISSUE THREAD

**Issue by Deadpool1994** [skywalker212/my-dictionary#1]
When a word is added which ends with a space it was not trimmed down as a result one cannot remove those words.

`app.post('/request',function (req,res) {
  words.push(req.body);
  res.json(words);
});` 

Have to use .trim() and than appends it on words array.

**Comment by skywalker212** [comment]
but won't it remove all the spaces in the array? I thought about using trim but then I thought that trim will also remove the space in the words and also at the end of the word and that's why I didn't use trim.
But now I found out that it removes all the leading and trailing whitespaces in the sentence!

Thanks!
